#프로젝트 전반에서 사용하는 상수를 정의

WORLD_WIDTH_SCALE   = 40
WORLD_HIGHT_SCALE   = 40

CREATURES_SIZE		= 50
CREATURE_MAX_HP		= 200
CREATURE_MAX_ENERGY	= 200
CREATURE_MAX_SPEED	= 3
CREATURE_BMR_ENERGY	= 3

FOODS_SIZE			= 30
FOOD_START_ENERGY	= 30

SUBSTANCE_A_ENERGY	= 1